steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/gleaming-city-447712-b0/mmlu-container/setup-container',
    '-f',
    'dockerfiles/setup.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/gleaming-city-447712-b0/mmlu-container/setup-container'
  ]
