[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops-55"
version = "0.1.0"
description = "Add your description here"
authors = [
  { name = "Andreas", email = "your@email.com" },
  { name = "Bertram", email = "your@email.com" },
  { name = "Rachael", email = "your@email.com" },
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pydantic",
    "pydantic-settings",
    "torch",
    "transformers",
    "datasets",
    "typer",
    "lightning>=2.5.0.post0",
    "hydra-core>=1.3.2",
    "rich>=13.9.4",
    "loguru>=0.7.3",
    "dvc",
    "dvc-gdrive",
    "dvc-gs",
]

[project.scripts]
train = "project.train:run"
cli = "project.cli:cli"
get-processed-datasets = "project.data:get_processed_datasets"

[project.optional-dependencies]
gpu = [
    "bitsandbytes>=0.43.2",
    "flash-attn<=2.6.2",
]

[dependency-groups]
dev = [
    "ruff",
    "codespell",
    "pre-commit",
    "ipython",
    "ipykernel",
    "invoke",
]

test = [
    "pytest",
    "pytest-check>=2.4.1",
    "coverage",
    "python-dotenv",
    "pipreqs",
    "mypy",
]

docs = [
  "mkdocs-material",
  "mkdocs-glightbox",
  "mkdocs-material-extensions",
  "pymdown-extensions",
  "mkdocs-same-dir",
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocs-exclude",
  "markdown-exec[ansi]"
]

[tool.uv]
default-groups = ["dev", "test", "docs"]
no-build-isolation-package = ["flash-attn"]

[tool.codespell]
skip = "*.pdf,*.ipynb,*.drawio,*.json"

[tool.coverage.run]
source = ["."]
omit = [
    "tests/*",
    "/tmp/*",
    "*/site-packages/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError"
]

[tool.typos.default.extend-identifiers]
arange = "arange"

[tool.typos.default.extend-words]
Ue = "Ue"
Hashi = "Hashi"

[tool.setuptools]
packages.find = {where = ["src"], include = ["project*"]}
