# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - datamodule/default
  - train/local
  - optimizer/sgd
  - _self_

project_name: "MMLU Classification"
