seed: 42
model_name: "answerdotai/ModernBERT-base"
device: "mps"
epochs: 1
batch_size: 32
eval_batch_size: 8
output_dir: "models/"
monitor: "val/loss"
mode: "min"
patience: 2
n_train_samples: 800
n_val_samples: 200
