name: check_data_changes

on:
  pull_request:
    branches:
    - main
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  check_data:
      name: Check data changes
      runs-on: ${{ matrix.operating-system }}
      strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12"]
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} #TODO: Ask Bertram about secret key for google

      - name: Pull data
        run: |
          dvc pull --no-run-cache

      - name: Check data 
        run: |
          python src/project/visualize.py > data_overview.md
          echo '![](./train_label_distribution.png "Train label distribution")' >> data_overview.md
          echo '![](./test_label_distribution.png "Test label distribution")' >> data_overview.md

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITTY_TOKEN }} #TODO: Ask Bertram to add 
        run: |
          cml comment create data_overview.md --watermark-title="Data Investigated" # (1)!

