name: DVC Workflow

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
    - main
    - dev
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.13"
        python-version: "3.12"
        enable-cache: true

    - name: Install the project
      run: uv sync

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Pull data
      run: |
        dvc pull --no-run-cache || true

    - name: Check data statistics
      run: |
        uv run stats

    - name: Check data statistics & generate report
      run: |
          python src/project/visualize.py > data_overview.md
          echo '![](./train_label_distribution.png "Train label distribution")' >> data_overview.md
          echo '![](./test_label_distribution.png "Test label distribution")' >> data_overview.md

    - name: Setup cml
      uses: iterative/setup-cml@v2

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!
