name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . .venv/bin/activate
          uv run coverage run --source=src/ -m pytest

      - name: Upload coverage report
        run: |
          echo '## Code Coverage Report' >> cov.md
          uv run coverage report -m --format="markdown" >> cov.md

      - name: Create a coverage comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const coverageReport = fs.readFileSync('cov.md', 'utf8');
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: coverageReport,
            });

      - name: Find coverage comment
        uses: peter-evans/find-comment@v3
        with:
          comment-author: github-actions[bot]
          body-includes: Coverage
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: bertramhojer/mlops-55
          direction: first
