name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --extra train --extra deployment

      - name: Run tests
        run: uv run coverage run --source=src/ -m pytest

      - name: Generate coverage report
        run: |
          echo '## Code Coverage Report' >> cov.md
          uv run coverage report -m --format="markdown" >> cov.md

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Coverage'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'cov.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          edit-mode: replace

